version: '3.8'
services:
  api:
    build: .
    restart: always
    env_file: .env
    ports:
      - '4000:4000'
    networks:
      - web-network
    depends_on:
      - db
      - cache

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web-network

  cache:
    image: redis:7.4-alpine
    restart: always
    networks:
      - web-network

networks:
  web-network:
    external: true

volumes:
  db_data:
